Refact/eam
viridIT/vBook pull request #41
Opened 2022-09-16 15:15 UTC by Mathieu-Lala

# Summary of changes

* add vsmtp logo + badge to introduction
* split the "Hardening vSMTP" into 3 sections (Open Relay / SPF / DKIM)
* move the Email Authentication Mechanism chapter in the "Terminology"
* merge the tuto/dkim&eam/dkim and tuto/spf&eam/spf pages

2022-09-16 15:26 UTC, ltabis requested changes

2022-09-16 15:26 UTC, ltabis commented on src/tuto/0/dkim.md
> +We will configure these rule:
"these rules"

2022-09-16 15:26 UTC, ltabis commented on src/tuto/0/dkim.md
> +- The sender is a Doe's family account : a DKIM signature is added to the message.
"The sender is an account from Doe's family."

2022-09-16 15:26 UTC, ltabis commented on src/tuto/0/dkim.md
> +- The recipient is a Doe's family account : the DKIM signatures are verified.
Same as last comment.

2022-09-16 15:26 UTC, ltabis commented on src/tuto/0/open-relay.md
> +- The recipient is a Doe's family account, whatever the sender is (incoming messages).
"The recipient is an account from Doe's family, whatever the sender is. (incoming messages)"

2022-09-16 15:26 UTC, ltabis commented on src/tuto/0/open-relay.md
> +- The sender is authenticated as a Doe's family account, whatever the recipient is (outgoing messages).
"The sender is authenticated as an account from Doe's family, whatever the recipient is. (outgoing messages)"

2022-09-17 14:39 UTC, ltabis approved these changes

2022-09-18 08:49 UTC, merged

2022-09-18 16:07 UTC, paguardiolle commented on src/tuto/0/spf.md
> +    rule "check spf" || check_spf("both", "soft"),
Imho same as DKIM. Requires a "if not internal" then spf else nothing.